name: Issue management

on:
  issues:
    types: [opened, assigned, closed]

# map fields with customized labels
env:
  todo: Todo
  assigned: Assigned
  done: Done

  project-owner: 'rob-demo'
  project-number: 1

jobs:
  issue-created:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' && github.repository == 'rob-demo/demo-actions'
    steps:
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@d93504a6ff913242c1c512d97ad1f8b302000af5
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - uses: monry/actions-add-issue-to-project@3e54e1f966203c08d6f15406f7dcf6f6ef2f7dd1
        id: add-issue-to-project
        with:
          # Personal Access Token that with `repo`, `org:read` and `org:write` are granted.
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          project-owner: ${{ env.project-owner }}
          project-number: ${{ env.project-number }}
          issue-id: ${{ github.event.issue.node_id }}

      - name: Moved issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@a6fc1cc9d210e0d1a8d35ec892c94b24881ce13e
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status

  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned' && github.repository == 'rob-demo/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@d93504a6ff913242c1c512d97ad1f8b302000af5
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.assigned }}
        uses: leonsteinhaeuser/project-beta-automations@a6fc1cc9d210e0d1a8d35ec892c94b24881ce13e
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.assigned }} # Target status

  issue-closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed' && github.repository == 'rob-demo/demo-actions'
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@d93504a6ff913242c1c512d97ad1f8b302000af5
        with:
          application_id: ${{ secrets.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
      
      - name: Move issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@a6fc1cc9d210e0d1a8d35ec892c94b24881ce13e
        with:
          gh_token: ${{ steps.get_workflow_token.outputs.token }}
          organization: ${{ env.project-owner }}
          project_id: ${{ env.project-number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
